/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type StoreSettings = {
  _id: string;
  _type: "storeSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  currency?: string;
  currencySymbol?: string;
  freeShippingThreshold?: number;
  shippingFlatRate?: number;
  taxRate?: number;
  lowStockThreshold?: number;
  loyaltyPointsPerDollar?: number;
  loyaltyPointValue?: number;
  supportEmail?: string;
  supportPhone?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type ProductVariantReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productVariant";
};

export type ProductWeightReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productWeight";
};

export type ProductSizeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productSize";
};

export type ProductColorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "productColor";
};

export type VendorProduct = {
  _id: string;
  _type: "vendorProduct";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  vendorEmail?: string;
  vendorName?: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  baseWeight?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  brand?: BrandReference;
  variant?: ProductVariantReference;
  hasWeights?: boolean;
  useAllWeights?: boolean;
  weights?: Array<
    {
      _key: string;
    } & ProductWeightReference
  >;
  hasVariants?: boolean;
  useAllSizes?: boolean;
  sizes?: Array<
    {
      _key: string;
    } & ProductSizeReference
  >;
  useAllColors?: boolean;
  colors?: Array<
    {
      _key: string;
    } & ProductColorReference
  >;
  profitMargin?: number;
  vendorProductStatus?:
    | "draft"
    | "pending"
    | "approved"
    | "rejected"
    | "active"
    | "inactive"
    | "pending_deactivation"
    | "pending_activation";
  approvalStatus?: "awaiting" | "approved" | "rejected";
  rejectionReason?: string;
  submittedAt?: string;
  approvedAt?: string;
  approvedBy?: string;
  mainProductId?: string;
  totalSales?: number;
  totalRevenue?: number;
  totalProfit?: number;
  lastOrderDate?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type UserReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "user";
};

export type VendorApplication = {
  _id: string;
  _type: "vendorApplication";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: UserReference;
  userId?: string;
  userEmail?: string;
  businessName?: string;
  businessType?:
    | "individual"
    | "partnership"
    | "llc"
    | "corporation"
    | "cooperative";
  businessDescription?: string;
  businessAddress?: string;
  businessPhone?: string;
  businessEmail?: string;
  taxId?: string;
  websiteUrl?: string;
  productsCategory?:
    | "fruits"
    | "vegetables"
    | "dairy"
    | "meat"
    | "bakery"
    | "organic"
    | "packaged"
    | "beverages"
    | "other";
  estimatedMonthlyRevenue?:
    | "0-1000"
    | "1000-5000"
    | "5000-10000"
    | "10000-25000"
    | "25000-50000"
    | "50000+";
  status?: "pending" | "reviewing" | "approved" | "rejected";
  appliedAt?: string;
  reviewedAt?: string;
  reviewedBy?: string;
  approvalNotes?: string;
  rejectionReason?: string;
  adminNotes?: string;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: ProductReference;
  user?: UserReference;
  rating?: number;
  title?: string;
  content?: string;
  isVerifiedPurchase?: boolean;
  status?: "pending" | "approved" | "rejected";
  helpful?: number;
  helpfulBy?: Array<
    {
      _key: string;
    } & UserReference
  >;
  adminNotes?: string;
  createdAt?: string;
  updatedAt?: string;
  approvedAt?: string;
  approvedBy?: string;
};

export type UserAccessRequest = {
  _id: string;
  _type: "userAccessRequest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  status?: "pending" | "approved" | "rejected";
  requestedAt?: string;
  approvedAt?: string;
  approvedBy?: UserReference;
  rejectedAt?: string;
  rejectedBy?: UserReference;
  notes?: string;
};

export type SentNotification = {
  _id: string;
  _type: "sentNotification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  notificationId?: string;
  title?: string;
  message?: string;
  type?: "promo" | "order" | "system" | "marketing" | "general";
  priority?: "low" | "medium" | "high" | "urgent";
  sentAt?: string;
  sentBy?: string;
  actionUrl?: string;
  recipientCount?: number;
  recipients?: Array<{
    email?: string;
    name?: string;
    delivered?: boolean;
    read?: boolean;
    readAt?: string;
    _key: string;
  }>;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  subject?: string;
  message?: string;
  status?: "new" | "read" | "replied" | "closed";
  priority?: "low" | "medium" | "high" | "urgent";
  submittedAt?: string;
  ipAddress?: string;
  userAgent?: string;
};

export type Address = {
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  user?: UserReference;
  phone?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  country?: string;
  countryCode?: string;
  stateCode?: string;
  subArea?: string;
  type?: "home" | "office" | "other";
  default?: boolean;
  createdAt?: string;
};

export type AddressReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "address";
};

export type OrderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "order";
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firebaseUid?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  dateOfBirth?: string;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  profileImageUrl?: string;
  addresses?: Array<
    {
      _key: string;
    } & AddressReference
  >;
  preferences?: {
    newsletter?: boolean;
    emailNotifications?: boolean;
    smsNotifications?: boolean;
    preferredCurrency?: "USD" | "EUR" | "GBP" | "CAD";
    preferredLanguage?: "en" | "es" | "fr" | "de";
  };
  rewardPoints?: number;
  wishlist?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  cart?: Array<{
    product?: ProductReference;
    quantity?: number;
    addedAt?: string;
    size?: string;
    color?: string;
    _key: string;
  }>;
  orders?: Array<
    {
      _key: string;
    } & OrderReference
  >;
  loyaltyPoints?: number;
  totalSpent?: number;
  walletBalance?: number;
  walletTransactions?: Array<{
    id?: string;
    type?:
      | "credit_refund"
      | "credit_manual"
      | "debit_order"
      | "debit_withdrawal";
    amount?: number;
    balanceBefore?: number;
    balanceAfter?: number;
    description?: string;
    orderId?: string;
    withdrawalRequestId?: string;
    processedBy?: string;
    createdAt?: string;
    status?: "completed" | "pending" | "failed" | "cancelled";
    _key: string;
  }>;
  withdrawalRequests?: Array<{
    id?: string;
    amount?: number;
    method?: "bank" | "paypal" | "stripe" | "check";
    bankDetails?: {
      accountHolderName?: string;
      bankName?: string;
      accountNumber?: string;
      routingNumber?: string;
      swiftCode?: string;
    };
    paypalEmail?: string;
    status?:
      | "pending"
      | "approved"
      | "processing"
      | "completed"
      | "rejected"
      | "cancelled";
    requestedAt?: string;
    processedAt?: string;
    processedBy?: string;
    rejectionReason?: string;
    notes?: string;
    transactionId?: string;
    _key: string;
  }>;
  lastLogin?: string;
  isActive?: boolean;
  role?: "user" | "admin" | "vendor" | "employee";
  isVendor?: boolean;
  vendorStatus?: "none" | "pending" | "active" | "rejected" | "suspended";
  vendorAppliedAt?: string;
  vendorApprovedBy?: string;
  vendorApprovedAt?: string;
  vendorRejectedAt?: string;
  vendorRejectionReason?: string;
  vendorSuspendedAt?: string;
  vendorSuspendedBy?: string;
  vendorSuspensionReason?: string;
  vendorBusinessName?: string;
  vendorBusinessDescription?: string;
  vendorBusinessLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  vendorCommissionRate?: number;
  vendorPerformance?: {
    totalProducts?: number;
    activeProducts?: number;
    totalSales?: number;
    totalRevenue?: number;
    totalCommission?: number;
    averageRating?: number;
    totalReviews?: number;
  };
  isEmployee?: boolean;
  isAdmin?: boolean;
  employeeRole?:
    | "callcenter"
    | "packer"
    | "warehouse"
    | "deliveryman"
    | "incharge"
    | "accounts";
  employeeStatus?: "active" | "inactive" | "suspended";
  employeeAssignedBy?: string;
  employeeAssignedAt?: string;
  employeeSuspendedBy?: string;
  employeeSuspendedAt?: string;
  employeeSuspensionReason?: string;
  employeePerformance?: {
    ordersProcessed?: number;
    ordersConfirmed?: number;
    ordersPacked?: number;
    ordersAssignedForDelivery?: number;
    ordersDelivered?: number;
    cashCollected?: number;
    paymentsReceived?: number;
    lastActiveAt?: string;
  };
  createdAt?: string;
  updatedAt?: string;
  notifications?: Array<{
    id?: string;
    title?: string;
    message?: string;
    type?: "promo" | "order" | "system" | "marketing" | "general";
    read?: boolean;
    priority?: "low" | "medium" | "high" | "urgent";
    sentAt?: string;
    readAt?: string;
    sentBy?: string;
    actionUrl?: string;
    _key: string;
  }>;
};

export type Blogcategory = {
  _id: string;
  _type: "blogcategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type BlogcategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogcategory";
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories?: Array<
    {
      _key: string;
    } & BlogcategoryReference
  >;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  buttonTitle?: string;
  buttonHref?: string;
};

export type CouponReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "coupon";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  firebaseUid?: string;
  clerkPaymentId?: string;
  clerkPaymentStatus?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  sslcommerzTransactionId?: string;
  sslcommerzSessionKey?: string;
  sslcommerzValidationId?: string;
  sslcommerzBankTransactionId?: string;
  sslcommerzCardType?: string;
  sslcommerzCardIssuer?: string;
  sslcommerzCardBrand?: string;
  sslcommerzCardNo?: string;
  sslcommerzTransactionDate?: string;
  paidAt?: string;
  products?: Array<{
    product?: ProductReference;
    quantity?: number;
    _key: string;
  }>;
  subtotal?: number;
  tax?: number;
  shipping?: number;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  productDiscount?: number;
  businessDiscount?: number;
  coupon?: {
    code?: string;
    discountType?: "percentage" | "fixed";
    discountValue?: number;
    discountAmount?: number;
    couponRef?: CouponReference;
  };
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?:
    | "pending"
    | "address_confirmed"
    | "order_confirmed"
    | "packed"
    | "ready_for_delivery"
    | "out_for_delivery"
    | "delivered"
    | "completed"
    | "cancelled"
    | "rescheduled"
    | "failed_delivery";
  orderDate?: string;
  paymentStatus?: "pending" | "paid" | "failed" | "cancelled";
  paymentMethod?:
    | "cash_on_delivery"
    | "stripe"
    | "sslcommerz"
    | "clerk"
    | "card";
  addressConfirmedBy?: string;
  addressConfirmedAt?: string;
  orderConfirmedBy?: string;
  orderConfirmedAt?: string;
  packedBy?: string;
  packedAt?: string;
  packingNotes?: string;
  assignedWarehouseBy?: string;
  assignedWarehouseAt?: string;
  dispatchedBy?: string;
  dispatchedAt?: string;
  assignedDeliverymanId?: string;
  assignedDeliverymanName?: string;
  deliveredBy?: string;
  deliveredAt?: string;
  deliveryNotes?: string;
  deliveryAttempts?: number;
  rescheduledDate?: string;
  rescheduledReason?: string;
  cashCollected?: boolean;
  cashCollectedAmount?: number;
  cashCollectedAt?: string;
  cashSubmittedToAccounts?: boolean;
  cashSubmittedBy?: string;
  cashSubmittedAt?: string;
  cashSubmissionNotes?: string;
  assignedAccountsEmployeeId?: string;
  assignedAccountsEmployeeName?: string;
  cashSubmissionStatus?: "not_submitted" | "pending" | "confirmed" | "rejected";
  cashSubmissionRejectionReason?: string;
  paymentReceivedBy?: string;
  paymentReceivedAt?: string;
  cancellationRequested?: boolean;
  cancellationRequestedAt?: string;
  cancellationRequestReason?: string;
  cancelledAt?: string;
  cancelledBy?: string;
  cancellationReason?: string;
  amountPaid?: number;
  refundedToWallet?: boolean;
  refundAmount?: number;
  statusHistory?: Array<{
    status?: string;
    changedBy?: string;
    changedByRole?:
      | "admin"
      | "callcenter"
      | "packer"
      | "warehouse"
      | "deliveryman"
      | "incharge"
      | "accounts"
      | "system";
    changedAt?: string;
    notes?: string;
    _key: string;
  }>;
};

export type Coupon = {
  _id: string;
  _type: "coupon";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  code?: string;
  description?: string;
  discountType?: "percentage" | "fixed";
  discountValue?: number;
  minimumOrderAmount?: number;
  maxDiscountAmount?: number;
  usageLimit?: number;
  usageLimitPerUser?: number;
  timesUsed?: number;
  startDate?: string;
  expiryDate?: string;
  isActive?: boolean;
  isPublic?: boolean;
  applicableProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  applicableCategories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  excludedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  firstOrderOnly?: boolean;
  userRestrictions?: Array<string>;
  createdAt?: string;
};

export type ProductColor = {
  _id: string;
  _type: "productColor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  hexCode?: string;
  isActive?: boolean;
  weight?: number;
  description?: string;
};

export type ProductSize = {
  _id: string;
  _type: "productSize";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  value?: string;
  isActive?: boolean;
  weight?: number;
  description?: string;
};

export type ProductWeight = {
  _id: string;
  _type: "productWeight";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  value?: string;
  unit?: "g" | "kg" | "lb" | "oz";
  numericValue?: number;
  isActive?: boolean;
  weight?: number;
  description?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  baseWeight?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  brand?: BrandReference;
  status?: "new" | "hot" | "sale";
  variant?: ProductVariantReference;
  hasWeights?: boolean;
  useAllWeights?: boolean;
  weights?: Array<
    {
      _key: string;
    } & ProductWeightReference
  >;
  hasVariants?: boolean;
  useAllSizes?: boolean;
  sizes?: Array<
    {
      _key: string;
    } & ProductSizeReference
  >;
  useAllColors?: boolean;
  colors?: Array<
    {
      _key: string;
    } & ProductColorReference
  >;
  isFeatured?: boolean;
  enableRatingsManagement?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
};

export type ProductVariant = {
  _id: string;
  _type: "productVariant";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  isActive?: boolean;
  weight?: number;
  seoTitle?: string;
  seoDescription?: string;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | StoreSettings
  | SanityImageAssetReference
  | CategoryReference
  | BrandReference
  | ProductVariantReference
  | ProductWeightReference
  | ProductSizeReference
  | ProductColorReference
  | VendorProduct
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | UserReference
  | VendorApplication
  | ProductReference
  | Review
  | UserAccessRequest
  | SentNotification
  | Contact
  | Address
  | AddressReference
  | OrderReference
  | User
  | Blogcategory
  | AuthorReference
  | BlogcategoryReference
  | Blog
  | BlockContent
  | Author
  | Banner
  | CouponReference
  | Order
  | Coupon
  | ProductColor
  | ProductSize
  | ProductWeight
  | Product
  | ProductVariant
  | Brand
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: app/(client)/payment-success/page.tsx
// Variable: query
// Query: *[_type == 'order' && firebaseUid == $userId] | order(orderDate desc){  ...,  products[]{    ...,product->  },  subtotal,  shipping,  tax,  totalPrice,  productDiscount,  amountDiscount,  businessDiscount,  coupon {    code,    discountType,    discountValue,    discountAmount  }}
export type QueryResult = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  firebaseUid?: string;
  clerkPaymentId?: string;
  clerkPaymentStatus?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  sslcommerzTransactionId?: string;
  sslcommerzSessionKey?: string;
  sslcommerzValidationId?: string;
  sslcommerzBankTransactionId?: string;
  sslcommerzCardType?: string;
  sslcommerzCardIssuer?: string;
  sslcommerzCardBrand?: string;
  sslcommerzCardNo?: string;
  sslcommerzTransactionDate?: string;
  paidAt?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      description?: string;
      price?: number;
      baseWeight?: number;
      discount?: number;
      categories?: Array<
        {
          _key: string;
        } & CategoryReference
      >;
      stock?: number;
      brand?: BrandReference;
      status?: "hot" | "new" | "sale";
      variant?: ProductVariantReference;
      hasWeights?: boolean;
      useAllWeights?: boolean;
      weights?: Array<
        {
          _key: string;
        } & ProductWeightReference
      >;
      hasVariants?: boolean;
      useAllSizes?: boolean;
      sizes?: Array<
        {
          _key: string;
        } & ProductSizeReference
      >;
      useAllColors?: boolean;
      colors?: Array<
        {
          _key: string;
        } & ProductColorReference
      >;
      isFeatured?: boolean;
      enableRatingsManagement?: boolean;
      averageRating?: number;
      totalReviews?: number;
      ratingDistribution?: {
        fiveStars?: number;
        fourStars?: number;
        threeStars?: number;
        twoStars?: number;
        oneStar?: number;
      };
    } | null;
    quantity?: number;
    _key: string;
  }> | null;
  subtotal: number | null;
  tax: number | null;
  shipping: number | null;
  totalPrice: number | null;
  currency?: string;
  amountDiscount: number | null;
  productDiscount: number | null;
  businessDiscount: number | null;
  coupon: {
    code: string | null;
    discountType: "fixed" | "percentage" | null;
    discountValue: number | null;
    discountAmount: number | null;
  } | null;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?:
    | "address_confirmed"
    | "cancelled"
    | "completed"
    | "delivered"
    | "failed_delivery"
    | "order_confirmed"
    | "out_for_delivery"
    | "packed"
    | "pending"
    | "ready_for_delivery"
    | "rescheduled";
  orderDate?: string;
  paymentStatus?: "cancelled" | "failed" | "paid" | "pending";
  paymentMethod?:
    | "card"
    | "cash_on_delivery"
    | "clerk"
    | "sslcommerz"
    | "stripe";
  addressConfirmedBy?: string;
  addressConfirmedAt?: string;
  orderConfirmedBy?: string;
  orderConfirmedAt?: string;
  packedBy?: string;
  packedAt?: string;
  packingNotes?: string;
  assignedWarehouseBy?: string;
  assignedWarehouseAt?: string;
  dispatchedBy?: string;
  dispatchedAt?: string;
  assignedDeliverymanId?: string;
  assignedDeliverymanName?: string;
  deliveredBy?: string;
  deliveredAt?: string;
  deliveryNotes?: string;
  deliveryAttempts?: number;
  rescheduledDate?: string;
  rescheduledReason?: string;
  cashCollected?: boolean;
  cashCollectedAmount?: number;
  cashCollectedAt?: string;
  cashSubmittedToAccounts?: boolean;
  cashSubmittedBy?: string;
  cashSubmittedAt?: string;
  cashSubmissionNotes?: string;
  assignedAccountsEmployeeId?: string;
  assignedAccountsEmployeeName?: string;
  cashSubmissionStatus?: "confirmed" | "not_submitted" | "pending" | "rejected";
  cashSubmissionRejectionReason?: string;
  paymentReceivedBy?: string;
  paymentReceivedAt?: string;
  cancellationRequested?: boolean;
  cancellationRequestedAt?: string;
  cancellationRequestReason?: string;
  cancelledAt?: string;
  cancelledBy?: string;
  cancellationReason?: string;
  amountPaid?: number;
  refundedToWallet?: boolean;
  refundAmount?: number;
  statusHistory?: Array<{
    status?: string;
    changedBy?: string;
    changedByRole?:
      | "accounts"
      | "admin"
      | "callcenter"
      | "deliveryman"
      | "incharge"
      | "packer"
      | "system"
      | "warehouse";
    changedAt?: string;
    notes?: string;
    _key: string;
  }>;
}>;

// Source: sanity/helpers/index.ts
// Variable: PRODUCT_BY_CATEGORY_QUERY
// Query: *[_type == 'product' && references(*[_type == "category" && slug.current == $categorySlug]._id)] | order(name asc)
export type PRODUCT_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  baseWeight?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  brand?: BrandReference;
  status?: "hot" | "new" | "sale";
  variant?: ProductVariantReference;
  hasWeights?: boolean;
  useAllWeights?: boolean;
  weights?: Array<
    {
      _key: string;
    } & ProductWeightReference
  >;
  hasVariants?: boolean;
  useAllSizes?: boolean;
  sizes?: Array<
    {
      _key: string;
    } & ProductSizeReference
  >;
  useAllColors?: boolean;
  colors?: Array<
    {
      _key: string;
    } & ProductColorReference
  >;
  isFeatured?: boolean;
  enableRatingsManagement?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
}>;

// Source: sanity/helpers/index.ts
// Variable: SALE_QUERY
// Query: *[_type == 'sale'] | order(name asc)
export type SALE_QUERY_RESULT = Array<never>;

// Source: sanity/helpers/index.ts
// Variable: MY_ORDERS_QUERY
// Query: *[_type == 'order' && firebaseUid == $userId] | order(orderDate desc)[$start...$end]{    ...,    paymentStatus,    paymentMethod,    productDiscount,    amountDiscount,    businessDiscount,    products[]{      ...,      product->{        _id,        name,        slug,        "image": images[0],        price      }    }  }
export type MY_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  firebaseUid?: string;
  clerkPaymentId?: string;
  clerkPaymentStatus?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  sslcommerzTransactionId?: string;
  sslcommerzSessionKey?: string;
  sslcommerzValidationId?: string;
  sslcommerzBankTransactionId?: string;
  sslcommerzCardType?: string;
  sslcommerzCardIssuer?: string;
  sslcommerzCardBrand?: string;
  sslcommerzCardNo?: string;
  sslcommerzTransactionDate?: string;
  paidAt?: string;
  products: Array<{
    product: {
      _id: string;
      name: string | null;
      slug: Slug | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      } | null;
      price: number | null;
    } | null;
    quantity?: number;
    _key: string;
  }> | null;
  subtotal?: number;
  tax?: number;
  shipping?: number;
  totalPrice?: number;
  currency?: string;
  amountDiscount: number | null;
  productDiscount: number | null;
  businessDiscount: number | null;
  coupon?: {
    code?: string;
    discountType?: "fixed" | "percentage";
    discountValue?: number;
    discountAmount?: number;
    couponRef?: CouponReference;
  };
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?:
    | "address_confirmed"
    | "cancelled"
    | "completed"
    | "delivered"
    | "failed_delivery"
    | "order_confirmed"
    | "out_for_delivery"
    | "packed"
    | "pending"
    | "ready_for_delivery"
    | "rescheduled";
  orderDate?: string;
  paymentStatus: "cancelled" | "failed" | "paid" | "pending" | null;
  paymentMethod:
    | "card"
    | "cash_on_delivery"
    | "clerk"
    | "sslcommerz"
    | "stripe"
    | null;
  addressConfirmedBy?: string;
  addressConfirmedAt?: string;
  orderConfirmedBy?: string;
  orderConfirmedAt?: string;
  packedBy?: string;
  packedAt?: string;
  packingNotes?: string;
  assignedWarehouseBy?: string;
  assignedWarehouseAt?: string;
  dispatchedBy?: string;
  dispatchedAt?: string;
  assignedDeliverymanId?: string;
  assignedDeliverymanName?: string;
  deliveredBy?: string;
  deliveredAt?: string;
  deliveryNotes?: string;
  deliveryAttempts?: number;
  rescheduledDate?: string;
  rescheduledReason?: string;
  cashCollected?: boolean;
  cashCollectedAmount?: number;
  cashCollectedAt?: string;
  cashSubmittedToAccounts?: boolean;
  cashSubmittedBy?: string;
  cashSubmittedAt?: string;
  cashSubmissionNotes?: string;
  assignedAccountsEmployeeId?: string;
  assignedAccountsEmployeeName?: string;
  cashSubmissionStatus?: "confirmed" | "not_submitted" | "pending" | "rejected";
  cashSubmissionRejectionReason?: string;
  paymentReceivedBy?: string;
  paymentReceivedAt?: string;
  cancellationRequested?: boolean;
  cancellationRequestedAt?: string;
  cancellationRequestReason?: string;
  cancelledAt?: string;
  cancelledBy?: string;
  cancellationReason?: string;
  amountPaid?: number;
  refundedToWallet?: boolean;
  refundAmount?: number;
  statusHistory?: Array<{
    status?: string;
    changedBy?: string;
    changedByRole?:
      | "accounts"
      | "admin"
      | "callcenter"
      | "deliveryman"
      | "incharge"
      | "packer"
      | "system"
      | "warehouse";
    changedAt?: string;
    notes?: string;
    _key: string;
  }>;
}>;

// Source: sanity/helpers/index.ts
// Variable: COUNT_QUERY
// Query: count(*[_type == 'order' && firebaseUid == $userId])
export type COUNT_QUERY_RESULT = number;

// Source: sanity/queries/query.ts
// Variable: BANNER_QUERY
// Query: *[_type == 'banner'] | order(publishedAt desc)
export type BANNER_QUERY_RESULT = Array<{
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  buttonTitle?: string;
  buttonHref?: string;
}>;

// Source: sanity/queries/query.ts
// Variable: FEATURED_CATEGORY_QUERY
// Query: *[_type == 'category' && featured == true] | order(name desc)
export type FEATURED_CATEGORY_QUERY_RESULT = Array<never>;

// Source: sanity/queries/query.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type=="product"] | order(name asc)
export type ALL_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  baseWeight?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  brand?: BrandReference;
  status?: "hot" | "new" | "sale";
  variant?: ProductVariantReference;
  hasWeights?: boolean;
  useAllWeights?: boolean;
  weights?: Array<
    {
      _key: string;
    } & ProductWeightReference
  >;
  hasVariants?: boolean;
  useAllSizes?: boolean;
  sizes?: Array<
    {
      _key: string;
    } & ProductSizeReference
  >;
  useAllColors?: boolean;
  colors?: Array<
    {
      _key: string;
    } & ProductColorReference
  >;
  isFeatured?: boolean;
  enableRatingsManagement?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
}>;

// Source: sanity/queries/query.ts
// Variable: FEATURE_PRODUCTS
// Query: *[_type == 'product' && isFeatured == true] | order(name asc){  ...,"categories": categories[]->title}
export type FEATURE_PRODUCTS_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  baseWeight?: number;
  discount?: number;
  categories: Array<string | null> | null;
  stock?: number;
  brand?: BrandReference;
  status?: "hot" | "new" | "sale";
  variant?: ProductVariantReference;
  hasWeights?: boolean;
  useAllWeights?: boolean;
  weights?: Array<
    {
      _key: string;
    } & ProductWeightReference
  >;
  hasVariants?: boolean;
  useAllSizes?: boolean;
  sizes?: Array<
    {
      _key: string;
    } & ProductSizeReference
  >;
  useAllColors?: boolean;
  colors?: Array<
    {
      _key: string;
    } & ProductColorReference
  >;
  isFeatured: true;
  enableRatingsManagement?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
}>;

// Source: sanity/queries/query.ts
// Variable: BRANDS_QUERY
// Query: *[_type=='brand'] | order(name asc)
export type BRANDS_QUERY_RESULT = Array<{
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;

// Source: sanity/queries/query.ts
// Variable: LATEST_BLOG_QUERY
// Query: *[_type == 'blog' && isLatest == true]|order(name asc){    ...,    blogcategories[]->{    title  }  }
export type LATEST_BLOG_QUERY_RESULT = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest: true;
  body?: BlockContent;
}>;

// Source: sanity/queries/query.ts
// Variable: GET_ALL_BLOG
// Query: *[_type == 'blog'] | order(publishedAt desc)[0...$quantity]{  ...,       blogcategories[]->{    title}    }
export type GET_ALL_BLOG_RESULT = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
}>;

// Source: sanity/queries/query.ts
// Variable: SINGLE_BLOG_QUERY
// Query: *[_type == "blog" && slug.current == $slug][0]{  ...,     author->{    name,    image,  },  blogcategories[]->{    title,    "slug": slug.current,  },}
export type SINGLE_BLOG_QUERY_RESULT = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
} | null;

// Source: sanity/queries/query.ts
// Variable: BLOG_CATEGORIES
// Query: *[_type == "blog"]{     blogcategories[]->{    ...    }  }
export type BLOG_CATEGORIES_RESULT = Array<{
  blogcategories: Array<{
    _id: string;
    _type: "blogcategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    description?: string;
  }> | null;
}>;

// Source: sanity/queries/query.ts
// Variable: OTHERS_BLOG_QUERY
// Query: *[  _type == "blog"  && defined(slug.current)  && slug.current != $slug]|order(publishedAt desc)[0...$quantity]{...  publishedAt,  title,  mainImage,  slug,  author->{    name,    image,  },  categories[]->{    title,    "slug": slug.current,  }}
export type OTHERS_BLOG_QUERY_RESULT = Array<{
  title: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  slug: Slug | null;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  categories: null;
}>;

// Source: sanity/queries/query.ts
// Variable: ADDRESS_QUERY
// Query: *[_type=="address"] | order(publishedAt desc)
export type ADDRESS_QUERY_RESULT = Array<{
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  user?: UserReference;
  phone?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  country?: string;
  countryCode?: string;
  stateCode?: string;
  subArea?: string;
  type?: "home" | "office" | "other";
  default?: boolean;
  createdAt?: string;
}>;

// Source: sanity/queries/query.ts
// Variable: ALLCATEGORIES_QUERY
// Query: *[_type == 'category'] | order(name asc) [0...$quantity]
export type ALLCATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;

// Source: sanity/queries/query.ts
// Variable: ADMIN_CATEGORIES_QUERY
// Query: *[_type == 'category'] | order(title asc) {    _id,    title,    slug,    description,    featured  }
export type ADMIN_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  featured: null;
}>;

// Source: sanity/queries/query.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug] | order(name asc) [0]{    ...,    "averageRating": math::avg(*[_type == "review" && product._ref == ^._id && status == "approved"].rating),    "totalReviews": count(*[_type == "review" && product._ref == ^._id && status == "approved"]),    variant->{      _id,      title,      slug    },    brand->{      _id,      title,      slug    },    categories[]->{      _id,      title,      slug    },    "weights": select(      useAllWeights == true => *[_type == "productWeight" && isActive == true] | order(weight asc) {        _id,        name,        value,        unit,        numericValue,        isActive      },      weights[]->{        _id,        name,        value,        unit,        numericValue,        isActive      }    ),    "sizes": select(      useAllSizes == true => *[_type == "productSize" && isActive == true] | order(weight asc) {        _id,        value,        isActive      },      sizes[]->{        _id,        value,        isActive      }    ),    "colors": select(      useAllColors == true => *[_type == "productColor" && isActive == true] | order(weight asc) {        _id,        name,        "value": hexCode,        isActive      },      colors[]->{        _id,        name,        "value": hexCode,        isActive      }    )  }
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  baseWeight?: number;
  discount?: number;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
  stock?: number;
  brand: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  status?: "hot" | "new" | "sale";
  variant: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  hasWeights?: boolean;
  useAllWeights?: boolean;
  weights:
    | Array<{
        _id: string;
        name: string | null;
        value: string | null;
        unit: "g" | "kg" | "lb" | "oz" | null;
        numericValue: number | null;
        isActive: true;
      }>
    | Array<{
        _id: string;
        name: string | null;
        value: string | null;
        unit: "g" | "kg" | "lb" | "oz" | null;
        numericValue: number | null;
        isActive: boolean | null;
      }>
    | null;
  hasVariants?: boolean;
  useAllSizes?: boolean;
  sizes:
    | Array<{
        _id: string;
        value: string | null;
        isActive: true;
      }>
    | Array<{
        _id: string;
        value: string | null;
        isActive: boolean | null;
      }>
    | null;
  useAllColors?: boolean;
  colors:
    | Array<{
        _id: string;
        name: string | null;
        value: string | null;
        isActive: true;
      }>
    | Array<{
        _id: string;
        name: string | null;
        value: string | null;
        isActive: boolean | null;
      }>
    | null;
  isFeatured?: boolean;
  enableRatingsManagement?: boolean;
  averageRating: number | null;
  totalReviews: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
} | null;

// Source: sanity/queries/query.ts
// Variable: RELATED_PRODUCTS_QUERY
// Query: *[_type == "product" && count((categories[]._ref)[@ in $categoryIds]) > 0 && slug.current != $currentSlug] | order(name asc) [0...$limit]{    _id,    name,    slug,    price,    discount,    stock,    images,    categories[]->{      _id,      title,      slug    }  }
export type RELATED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
}>;

// Source: sanity/queries/query.ts
// Variable: BRAND_QUERY
// Query: *[_type == "product" && slug.current == $slug]{"brandName": brand->title}
export type BRAND_QUERY_RESULT = Array<{
  brandName: string | null;
}>;

// Source: sanity/queries/query.ts
// Variable: PRODUCTS_BY_VARIANT_QUERY
// Query: *[_type == "product" && variant->slug.current == $variantSlug] | order(name asc) {    ...,    variant->{      _id,      title,      slug,      description,      image    },    brand->{      _id,      title,      slug    },    categories[]->{      _id,      title,      slug    },    "averageRating": math::avg(*[_type == "review" && product._ref == ^._id && status == "approved"].rating),    "totalReviews": count(*[_type == "review" && product._ref == ^._id && status == "approved"])  }
export type PRODUCTS_BY_VARIANT_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  baseWeight?: number;
  discount?: number;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
  stock?: number;
  brand: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  status?: "hot" | "new" | "sale";
  variant: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    description: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  hasWeights?: boolean;
  useAllWeights?: boolean;
  weights?: Array<
    {
      _key: string;
    } & ProductWeightReference
  >;
  hasVariants?: boolean;
  useAllSizes?: boolean;
  sizes?: Array<
    {
      _key: string;
    } & ProductSizeReference
  >;
  useAllColors?: boolean;
  colors?: Array<
    {
      _key: string;
    } & ProductColorReference
  >;
  isFeatured?: boolean;
  enableRatingsManagement?: boolean;
  averageRating: number | null;
  totalReviews: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
}>;

// Source: sanity/queries/query.ts
// Variable: VARIANT_BY_SLUG_QUERY
// Query: *[_type == "productVariant" && slug.current == $slug][0]{    _id,    title,    slug,    description,    image,    seoTitle,    seoDescription,    "productCount": count(*[_type == "product" && variant._ref == ^._id])  }
export type VARIANT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seoTitle: string | null;
  seoDescription: string | null;
  productCount: number;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == 'order' && firebaseUid == $userId] | order(orderDate desc){\n  ...,\n  products[]{\n    ...,product->\n  },\n  subtotal,\n  shipping,\n  tax,\n  totalPrice,\n  productDiscount,\n  amountDiscount,\n  businessDiscount,\n  coupon {\n    code,\n    discountType,\n    discountValue,\n    discountAmount\n  }\n}": QueryResult;
    "*[_type == 'product' && references(*[_type == \"category\" && slug.current == $categorySlug]._id)] | order(name asc)": PRODUCT_BY_CATEGORY_QUERY_RESULT;
    "*[_type == 'sale'] | order(name asc)": SALE_QUERY_RESULT;
    "*[_type == 'order' && firebaseUid == $userId] | order(orderDate desc)[$start...$end]{\n    ...,\n    paymentStatus,\n    paymentMethod,\n    productDiscount,\n    amountDiscount,\n    businessDiscount,\n    products[]{\n      ...,\n      product->{\n        _id,\n        name,\n        slug,\n        \"image\": images[0],\n        price\n      }\n    }\n  }": MY_ORDERS_QUERY_RESULT;
    "count(*[_type == 'order' && firebaseUid == $userId])": COUNT_QUERY_RESULT;
    "*[_type == 'banner'] | order(publishedAt desc)": BANNER_QUERY_RESULT;
    "*[_type == 'category' && featured == true] | order(name desc)": FEATURED_CATEGORY_QUERY_RESULT;
    '*[_type=="product"] | order(name asc)': ALL_PRODUCTS_QUERY_RESULT;
    "*[_type == 'product' && isFeatured == true] | order(name asc){\n  ...,\"categories\": categories[]->title\n}": FEATURE_PRODUCTS_RESULT;
    "*[_type=='brand'] | order(name asc) ": BRANDS_QUERY_RESULT;
    " *[_type == 'blog' && isLatest == true]|order(name asc){\n    ...,\n    blogcategories[]->{\n    title\n  }\n  }": LATEST_BLOG_QUERY_RESULT;
    "*[_type == 'blog'] | order(publishedAt desc)[0...$quantity]{\n  ...,  \n     blogcategories[]->{\n    title\n}\n    }\n  ": GET_ALL_BLOG_RESULT;
    '*[_type == "blog" && slug.current == $slug][0]{\n  ..., \n    author->{\n    name,\n    image,\n  },\n  blogcategories[]->{\n    title,\n    "slug": slug.current,\n  },\n}': SINGLE_BLOG_QUERY_RESULT;
    '*[_type == "blog"]{\n     blogcategories[]->{\n    ...\n    }\n  }': BLOG_CATEGORIES_RESULT;
    '*[\n  _type == "blog"\n  && defined(slug.current)\n  && slug.current != $slug\n]|order(publishedAt desc)[0...$quantity]{\n...\n  publishedAt,\n  title,\n  mainImage,\n  slug,\n  author->{\n    name,\n    image,\n  },\n  categories[]->{\n    title,\n    "slug": slug.current,\n  }\n}': OTHERS_BLOG_QUERY_RESULT;
    '*[_type=="address"] | order(publishedAt desc)': ADDRESS_QUERY_RESULT;
    "*[_type == 'category'] | order(name asc) [0...$quantity]": ALLCATEGORIES_QUERY_RESULT;
    "*[_type == 'category'] | order(title asc) {\n    _id,\n    title,\n    slug,\n    description,\n    featured\n  }": ADMIN_CATEGORIES_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug] | order(name asc) [0]{\n    ...,\n    "averageRating": math::avg(*[_type == "review" && product._ref == ^._id && status == "approved"].rating),\n    "totalReviews": count(*[_type == "review" && product._ref == ^._id && status == "approved"]),\n    variant->{\n      _id,\n      title,\n      slug\n    },\n    brand->{\n      _id,\n      title,\n      slug\n    },\n    categories[]->{\n      _id,\n      title,\n      slug\n    },\n    "weights": select(\n      useAllWeights == true => *[_type == "productWeight" && isActive == true] | order(weight asc) {\n        _id,\n        name,\n        value,\n        unit,\n        numericValue,\n        isActive\n      },\n      weights[]->{\n        _id,\n        name,\n        value,\n        unit,\n        numericValue,\n        isActive\n      }\n    ),\n    "sizes": select(\n      useAllSizes == true => *[_type == "productSize" && isActive == true] | order(weight asc) {\n        _id,\n        value,\n        isActive\n      },\n      sizes[]->{\n        _id,\n        value,\n        isActive\n      }\n    ),\n    "colors": select(\n      useAllColors == true => *[_type == "productColor" && isActive == true] | order(weight asc) {\n        _id,\n        name,\n        "value": hexCode,\n        isActive\n      },\n      colors[]->{\n        _id,\n        name,\n        "value": hexCode,\n        isActive\n      }\n    )\n  }': PRODUCT_BY_SLUG_QUERY_RESULT;
    '*[_type == "product" && count((categories[]._ref)[@ in $categoryIds]) > 0 && slug.current != $currentSlug] | order(name asc) [0...$limit]{\n    _id,\n    name,\n    slug,\n    price,\n    discount,\n    stock,\n    images,\n    categories[]->{\n      _id,\n      title,\n      slug\n    }\n  }': RELATED_PRODUCTS_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug]{\n"brandName": brand->title\n}': BRAND_QUERY_RESULT;
    '*[_type == "product" && variant->slug.current == $variantSlug] | order(name asc) {\n    ...,\n    variant->{\n      _id,\n      title,\n      slug,\n      description,\n      image\n    },\n    brand->{\n      _id,\n      title,\n      slug\n    },\n    categories[]->{\n      _id,\n      title,\n      slug\n    },\n    "averageRating": math::avg(*[_type == "review" && product._ref == ^._id && status == "approved"].rating),\n    "totalReviews": count(*[_type == "review" && product._ref == ^._id && status == "approved"])\n  }': PRODUCTS_BY_VARIANT_QUERY_RESULT;
    '*[_type == "productVariant" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    description,\n    image,\n    seoTitle,\n    seoDescription,\n    "productCount": count(*[_type == "product" && variant._ref == ^._id])\n  }': VARIANT_BY_SLUG_QUERY_RESULT;
  }
}
